//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMA.Blazor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PMA.Blazor.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle light / dark theme.
        /// </summary>
        public static string DarkModeButtonComponent_TooltipText {
            get {
                return ResourceManager.GetString("DarkModeButtonComponent.TooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteButtonComponent_Text {
            get {
                return ResourceManager.GetString("DeleteButtonComponent.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID: {0}.
        /// </summary>
        public static string EntryTextFieldComponent_HelperText {
            get {
                return ResourceManager.GetString("EntryTextFieldComponent.HelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Entry.
        /// </summary>
        public static string EntryTextFieldComponent_Label {
            get {
                return ResourceManager.GetString("EntryTextFieldComponent.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ID for entry &apos;{0}&apos;.
        /// </summary>
        public static string GetEntryIdContainerComponent_Title {
            get {
                return ResourceManager.GetString("GetEntryIdContainerComponent.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        public static string GetEntryIdTableComponent_BaseColumnHeader {
            get {
                return ResourceManager.GetString("GetEntryIdTableComponent.BaseColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry.
        /// </summary>
        public static string GetEntryIdTableComponent_EntryColumnHeader {
            get {
                return ResourceManager.GetString("GetEntryIdTableComponent.EntryColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string GetEntryIdTableComponent_IdColumnHeader {
            get {
                return ResourceManager.GetString("GetEntryIdTableComponent.IdColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {first_item}-{last_item} of {all_items}.
        /// </summary>
        public static string GetEntryIdTableComponent_InfoFormat {
            get {
                return ResourceManager.GetString("GetEntryIdTableComponent.InfoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Virtual.
        /// </summary>
        public static string GetEntryIdTableComponent_IsVirtualColumnHeader {
            get {
                return ResourceManager.GetString("GetEntryIdTableComponent.IsVirtualColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Entry.
        /// </summary>
        public static string GetEntryIdTableComponent_LeftColumnHeader {
            get {
                return ResourceManager.GetString("GetEntryIdTableComponent.LeftColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching records found.
        /// </summary>
        public static string GetEntryIdTableComponent_NoRecords {
            get {
                return ResourceManager.GetString("GetEntryIdTableComponent.NoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morph. Parameters.
        /// </summary>
        public static string GetEntryIdTableComponent_ParameterColumnHeader {
            get {
                return ResourceManager.GetString("GetEntryIdTableComponent.ParameterColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Entry.
        /// </summary>
        public static string GetEntryIdTableComponent_RightColumnHeader {
            get {
                return ResourceManager.GetString("GetEntryIdTableComponent.RightColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows Per Page.
        /// </summary>
        public static string GetEntryIdTableComponent_RowsPerPageString {
            get {
                return ResourceManager.GetString("GetEntryIdTableComponent.RowsPerPageString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort By.
        /// </summary>
        public static string GetEntryIdTableComponent_SortLabel {
            get {
                return ResourceManager.GetString("GetEntryIdTableComponent.SortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter pali-word.
        /// </summary>
        public static string InputTextFieldComponent_Label {
            get {
                return ResourceManager.GetString("InputTextFieldComponent.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Virtual.
        /// </summary>
        public static string IsVirtualCheckboxComponent_Label {
            get {
                return ResourceManager.GetString("IsVirtualCheckboxComponent.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer.
        /// </summary>
        public static string LayerSelectComponent_Label {
            get {
                return ResourceManager.GetString("LayerSelectComponent.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string LayerSelectComponent_Layer_0 {
            get {
                return ResourceManager.GetString("LayerSelectComponent.Layer.0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string LayerSelectComponent_Layer_1 {
            get {
                return ResourceManager.GetString("LayerSelectComponent.Layer.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string LayerSelectComponent_Layer_2 {
            get {
                return ResourceManager.GetString("LayerSelectComponent.Layer.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string LayerSelectComponent_Layer_3 {
            get {
                return ResourceManager.GetString("LayerSelectComponent.Layer.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string LayerSelectComponent_Layer_4 {
            get {
                return ResourceManager.GetString("LayerSelectComponent.Layer.4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string LayerSelectComponent_Layer_5 {
            get {
                return ResourceManager.GetString("LayerSelectComponent.Layer.5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        public static string LayerSelectComponent_Layer_6 {
            get {
                return ResourceManager.GetString("LayerSelectComponent.Layer.6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        public static string LayerSelectComponent_Layer_7 {
            get {
                return ResourceManager.GetString("LayerSelectComponent.Layer.7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        public static string LayerSelectComponent_Layer_8 {
            get {
                return ResourceManager.GetString("LayerSelectComponent.Layer.8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Chronological Layer.
        /// </summary>
        public static string LayerSelectComponent_TooltipText {
            get {
                return ResourceManager.GetString("LayerSelectComponent.TooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Entry.
        /// </summary>
        public static string LeftEntrySwitchComponent_Label {
            get {
                return ResourceManager.GetString("LeftEntrySwitchComponent.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Left Entry.
        /// </summary>
        public static string LeftEntryTextFieldComponent_Label {
            get {
                return ResourceManager.GetString("LeftEntryTextFieldComponent.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Entry ID.
        /// </summary>
        public static string LockEntryIdSwitchComponent_Label {
            get {
                return ResourceManager.GetString("LockEntryIdSwitchComponent.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth.
        /// </summary>
        public static string MaxDepthLevelNumericFieldComponent_Label {
            get {
                return ResourceManager.GetString("MaxDepthLevelNumericFieldComponent.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Max Depth Level.
        /// </summary>
        public static string MaxDepthLevelNumericFieldComponent_TooltipText {
            get {
                return ResourceManager.GetString("MaxDepthLevelNumericFieldComponent.TooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ModalDialog_Buttons_Cancel {
            get {
                return ResourceManager.GetString("ModalDialog.Buttons.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string ModalDialog_Buttons_No {
            get {
                return ResourceManager.GetString("ModalDialog.Buttons.No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ModalDialog_Buttons_Ok {
            get {
                return ResourceManager.GetString("ModalDialog.Buttons.Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string ModalDialog_Buttons_Yes {
            get {
                return ResourceManager.GetString("ModalDialog.Buttons.Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to both.
        /// </summary>
        public static string MorphBase_Both {
            get {
                return ResourceManager.GetString("MorphBase.Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        public static string MorphBase_Left {
            get {
                return ResourceManager.GetString("MorphBase.Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n/a.
        /// </summary>
        public static string MorphBase_None {
            get {
                return ResourceManager.GetString("MorphBase.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right.
        /// </summary>
        public static string MorphBase_Right {
            get {
                return ResourceManager.GetString("MorphBase.Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;unknown&gt;.
        /// </summary>
        public static string MorphBase_Unknown {
            get {
                return ResourceManager.GetString("MorphBase.Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Morphological Base.
        /// </summary>
        public static string MorphBaseSelectComponent_Label {
            get {
                return ResourceManager.GetString("MorphBaseSelectComponent.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show / hide morphological properties.
        /// </summary>
        public static string MorphPropertyButtonComponent_TooltipText {
            get {
                return ResourceManager.GetString("MorphPropertyButtonComponent.TooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string MorphPropertyPanelComponent_Title {
            get {
                return ResourceManager.GetString("MorphPropertyPanelComponent.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        public static string MorphRuleContainerComponent_Title {
            get {
                return ResourceManager.GetString("MorphRuleContainerComponent.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string MorphRuleTableComponent_DescriptionColumnHeader {
            get {
                return ResourceManager.GetString("MorphRuleTableComponent.DescriptionColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string MorphRuleTableComponent_IdColumnHeader {
            get {
                return ResourceManager.GetString("MorphRuleTableComponent.IdColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ResetButtonComponent_Text {
            get {
                return ResourceManager.GetString("ResetButtonComponent.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Entry.
        /// </summary>
        public static string RightEntrySwitchComponent_Label {
            get {
                return ResourceManager.GetString("RightEntrySwitchComponent.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Right Entry.
        /// </summary>
        public static string RightEntryTextFieldComponent_Label {
            get {
                return ResourceManager.GetString("RightEntryTextFieldComponent.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morhological rules.
        /// </summary>
        public static string RuleType_Morphological {
            get {
                return ResourceManager.GetString("RuleType.Morphological", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sandhi rules.
        /// </summary>
        public static string RuleType_Sandhi {
            get {
                return ResourceManager.GetString("RuleType.Sandhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButtonComponent_Text {
            get {
                return ResourceManager.GetString("SaveButtonComponent.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchTextFieldComponent_Placeholder {
            get {
                return ResourceManager.GetString("SearchTextFieldComponent.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string StartButtonComponent_StartText {
            get {
                return ResourceManager.GetString("StartButtonComponent.StartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string StartButtonComponent_StopText {
            get {
                return ResourceManager.GetString("StartButtonComponent.StopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string StartMorphAnalysisButtonComponent_StartText {
            get {
                return ResourceManager.GetString("StartMorphAnalysisButtonComponent.StartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string StartMorphAnalysisButtonComponent_StopText {
            get {
                return ResourceManager.GetString("StartMorphAnalysisButtonComponent.StopText", resourceCulture);
            }
        }
    }
}
